# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
